// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import JoinRoomReducer from "../join_room_reducer";
import SetPositionReducer from "../set_position_reducer";
import SetTopicReducer from "../set_topic_reducer";
import StartGameReducer from "../start_game_reducer";
import SwingReducer from "../swing_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type SetPositionParams = __Infer<typeof SetPositionReducer>;
export type SetTopicParams = __Infer<typeof SetTopicReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type SwingParams = __Infer<typeof SwingReducer>;

