// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomCode: __t.string().name("room_code"),
  wave: __t.u32(),
  seq: __t.u32(),
  size: __t.string(),
  target: __t.identity(),
  fromX: __t.f32().name("from_x"),
  fromY: __t.f32().name("from_y"),
  fromZ: __t.f32().name("from_z"),
  toX: __t.f32().name("to_x"),
  toZ: __t.f32().name("to_z"),
  spawnAt: __t.timestamp().name("spawn_at"),
  dead: __t.bool(),
  hitBy: __t.identity().name("hit_by"),
});
