// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Monster = __t.object("Monster", {
  id: __t.u32(),
  roomCode: __t.string(),
  kind: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
});
export type Monster = __Infer<typeof Monster>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  roomCode: __t.string(),
  name: __t.string(),
  color: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  tools: __t.array(__t.string()),
  connected: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const Room = __t.object("Room", {
  code: __t.string(),
  host: __t.identity(),
  topic: __t.string(),
  contentJson: __t.string(),
  phase: __t.string(),
  currentWorld: __t.u32(),
});
export type Room = __Infer<typeof Room>;

